name: Validate JSON files

on:
  pull_request:
    branches:
      - master

jobs:
  validate_configurations:
    name: Validate configurations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate studios.json
        uses: snapcart/json-schema-validator@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json_schema: .github/studios.schema.json
          json_path_pattern: studios.json
